### ISSUE TITLE
`make deploy` sometimes opens the file the user's editor

### ISSUE THREAD

**Issue by alexzaworski** [jh3y/crayon#1]
Hiya,

When I run `make deploy` I'm greeted with a sublime text window— I think if you instead `open` an actual URL (ie serve the file via `localhost` and open that) it should work regardless of how the user has configured the opening of `.html` files.

**Comment by jh3y** [comment]
Hey @alexzaworski 

Yeah that makes complete sense. Hmm. My only issue is how to open the `.html` file cross-platform I guess. In addition, if it's served by `localhost` then the user is required to take down `localhost` once it's posted which might not be best.

Maybe I should just make it clear that the file needs to just be opened in a browser.

@jh3y

**Comment by alexzaworski** [comment]
Fair points! No idea how to handle cross-platform stuff— totally outside of my wheelhouse unfortunately :( 

I found [this](http://stackoverflow.com/a/10250717) but I'm not sure it'll help here.

**Comment by jh3y** [comment]
Yeah took a read of that, interesting but seems it won't be too helpful here. Looks like the effort required would significantly outweigh the benefits.

Hmm. I'll make some notes on the `README`.

It's a good spot regardless 😄  👍 

@jh3y
